name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face
        run: |
          git remote add huggingface https://huggingface.co/spaces/Nithin89/AI_Reaserch_Buddy
          git push --force huggingface main
